version: '3.7'

services:
  api-tests:
    image: python:v1
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/workspace
    command: /bin/sh -c "STAGE=$$STAGE pytest -sv --alluredir=allure-results"
    working_dir: /usr/workspace
    environment:
      STAGE: prod
      API_TOKEN: ${API_TOKEN}
